apiVesrion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/didin2003/laravel-kubernetes.git
    targetRevision: HEAD
    path: frontend
    destination:
      server: https://kubernetes.default.svc
      namespace: apps
    syncPolicy:
      automated:
        prune: true
        selfHeal: true